baseurl: https://example.com/
languageCode: en-us
title: HugoCast
theme: castanet
googleAnalytics: ''
paginate: '9'
buildFuture: yes
taxonomies:
  category: categories
  series: series
  tag: tags
permalinks:
  about: /:filename/
  episode: /:filename/
Menu:
  Main:
    - identifier: about
      name: About
      url: /about
    - identifier: contact
      name: Contact
      url: /contact
    - identifier: hosts
      name: Hosts
      url: /host
    - identifier: guests
      name: Guests
      url: /guest
    - identifier: upcoming
      name: Upcoming Episodes
      url: /upcoming
    - identifier: blog
      name: Blog
      url: /blog
    - identifier: resources
      name: Resources
      url: '#!'
    - identifier: books
      name: Books
      parent: resources
      url: /books
    - identifier: podcasts
      name: Podcasts
      parent: resources
      url: /books
    - identifier: internet
      name: Internet
      url: https://www.google.com
params:
  android_subscribe: http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U
  authors:
    Bridget:
      bio: ''
      name: Bridget Kromhout
      social:
        twitter: bridgetkromhout
      thumbnail: img/host/bridget.jpg
    Matt:
      bio: Matt Stratton is a solutions architect at Chef, where he demonstrates how
        Chef’s automation platform provides speed and flexibility to clients’ infrastructure.
        He is devoted to concepts like Continuous Delivery and Infrastructure as Code,
        and his license plate actually says “DevOps”. He lives in Chicago and has
        an unhealthy obsession with Doctor Who, Firefly, and Game of Thrones. And
        whiskey.
      name: Matt Stratton
      social:
        facebook: matt.stratton
        github: mattstratton
        homepage: https://www.mattstratton.io
        instagram: instagram
        linkedin: mattstratton
        pinterest: mattstratton
        twitch: mattstratton
        twitter: mattstratton
        youtube: mattstratton
      thumbnail: img/host/matt.png
    Trevor:
      bio: ''
      name: Trevor Hess
      social:
        twitter: trevorghess
      thumbnail: img/host/trevor.jpg
  copyright_notice: Copyright 2016 [Matt Stratton](https://www.mattstrattion.io)
  description: The HugoCast is the best podcast you've ever seen. You will learn everything
    you ever needed to know about [podcasting](https://en.wikipedia.org/wiki/Podcast)
    from the most inspiring experts to ever show up on the whole internet.
  disable_title_caps: 'true'
  disqusShortname: ''
  enable_jumbo: 'true'
  episode_number_prefix: CWC
  episode_number_style: brackets
  feed:
    copyright: Copyright 2020 Matt Stratton
    itunes_author: Matt Stratton
    itunes_first_sub_category: Software How-To
    itunes_image: https://www.arresteddevops.com/img/ado-podcast-logo.png
    itunes_owner_email: matt.stratton@gmail.com
    itunes_owner_name: Matt Stratton
    itunes_second_sub_category: Tech News
    itunes_subtitle: The best podcast ever
    itunes_summary: The HugoCast is the best podcast you've ever seen. You will learn
      everything you ever needed to know about podcasting from the most inspiring
      experts to ever show up on the whole internet.
    itunes_top_category: Technology
    language: en-us
  google_play_subscribe: https://podcasts.google.com/feed/aHR0cHM6Ly93d3cuYXJyZXN0ZWRkZXZvcHMuY29tL2VwaXNvZGUvaW5kZXgueG1s
  googleAnalytics_UA: ''
  itunes_subscribe: https://podcasts.apple.com/us/podcast/arrested-devops/id773888088?ign-mpt=uo%3D4&mt=2
  links:
    ado:
      name: Arrested DevOps
      url: https://www.arresteddevops.com
    ffs:
      name: Food Fight Show
      url: https://foodfightshow.org
    sdt:
      name: Software Defined Talk
      url: https://cote.io/podcasts/sdt/
  mailchimp_subscribe: //arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc
  mainSections: episode
  media_prefix: https://media.blubrry.com/arresteddevops/content.blubrry.com/arresteddevops/
  pocketcasts_subscribe: http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss
  podlove:
    subscribe_color: '#585e6c'
    subscribe_cover: img/logo.jpg
    subscribe_description: ''
    subscribe_feed_format: mp3
    subscribe_feed_type: audio
    subscribe_format: rectangle
    subscribe_language: de
    subscribe_size: medium
    subscribe_style: filled
    subscribe_subtitle: ''
    subscribe_title: ''
  realfavicongenerator:
    mask_icon_color: '#5bbad5'
    msapplication_tilecolor: '#2b5797'
    theme_color: '#ffffff'
  show_next_upcoming: 'true'
  site_layout: row
  site_theme: blue
  social:
    facebook: Arresteddevops
    facebook_admin:
      - '500557137'
      - '1234'
    github: arresteddevops
    gitlab: mattstratton
    instagram: nozzleio
    linkedin: https://www.linkedin.com/company/linkedin/
    mastodon: https://hachyderm.io/@mattstratton
    pinterest: nozzleio
    threads: mattstratton
    twitch: mattstratton
    twitter: https://twitter.com/arresteddevops
    twitter_domain: arresteddevops.com
    youtube: arresteddevops
  soundcloud_subscribe: http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss
  spotify_subscribe: https://open.spotify.com/show/...
  stitcher_subscribe: http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops
  youtube_subscribe: https://www.youtube.com/arresteddevops?sub_confirmation=1
